_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BCRF_HEAD:
    DOWN_FACTOR: 2
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
